language: python
before_install:
 - sudo apt-get install -qq liblzma-dev
python:
 - "2.6"
 - "2.7"
install:
 - pip install -r requirements.txt
 - pip install .
# command to run tests
script:
 - make test
